const textBehindImageConstants = {
  randomWords: [
    "apple",
    "orange",
    "banana",
    "grape",
    "melon",
    "peach",
    "berry",
    "cherry",
    "lemon",
    "mango",
    "cloud",
    "storm",
    "rain",
    "thunder",
    "lightning",
    "wind",
    "breeze",
    "snow",
    "hail",
    "fog",
    "mountain",
    "valley",
    "hill",
    "river",
    "ocean",
    "lake",
    "forest",
    "jungle",
    "desert",
    "island",
    "sunrise",
    "sunset",
    "twilight",
    "moonlight",
    "starlight",
    "dawn",
    "dusk",
    "midnight",
    "noon",
    "evening",
    "shadow",
    "light",
    "dark",
    "glow",
    "spark",
    "flare",
    "flash",
    "shine",
    "beam",
    "luster",
    "dream",
    "vision",
    "fantasy",
    "wonder",
    "miracle",
    "mystery",
    "puzzle",
    "secret",
    "truth",
    "wisdom",
    "energy",
    "power",
    "strength",
    "force",
    "spirit",
    "soul",
    "mind",
    "thought",
    "idea",
    "inspiration",
    "fire",
    "water",
    "earth",
    "air",
    "metal",
    "wood",
    "stone",
    "crystal",
    "gold",
    "silver",
    "echo",
    "whisper",
    "voice",
    "song",
    "melody",
    "rhythm",
    "harmony",
    "tune",
    "symphony",
    "chorus",
    "peace",
    "love",
    "joy",
    "happiness",
    "hope",
    "faith",
    "kindness",
    "patience",
    "honor",
    "respect",
    "brave",
    "bold",
    "fearless",
    "strong",
    "gentle",
    "calm",
    "wild",
    "fierce",
    "silent",
    "loud",
    "cosmic",
    "galaxy",
    "universe",
    "star",
    "planet",
    "comet",
    "asteroid",
    "nebula",
    "orbit",
    "gravity",
    "time",
    "space",
    "infinity",
    "eternal",
    "limitless",
    "endless",
    "boundless",
    "timeless",
    "moment",
    "era",
    "zenith",
    "apex",
    "summit",
    "peak",
    "pinnacle",
    "height",
    "altitude",
    "horizon",
    "expanse",
    "beyond",
    "shadow",
    "phantom",
    "specter",
    "ghost",
    "spirit",
    "soul",
    "mystic",
    "oracle",
    "seer",
    "prophet",
    "flame",
    "ember",
    "blaze",
    "inferno",
    "firestorm",
    "pyro",
    "ignite",
    "burn",
    "scorch",
    "charcoal",
    "swift",
    "rapid",
    "fast",
    "quick",
    "lightning",
    "speed",
    "velocity",
    "momentum",
    "dash",
    "sprint",
    "deep",
    "vast",
    "profound",
    "boundless",
    "infinite",
    "expansive",
    "wide",
    "broad",
    "endless",
    "immeasurable",
    "frost",
    "ice",
    "glacier",
    "snowflake",
    "cold",
    "freeze",
    "chill",
    "crystal",
    "shiver",
    "icy",
    "arcane",
    "mystical",
    "enigmatic",
    "occult",
    "esoteric",
    "sacred",
    "hidden",
    "unknown",
    "forbidden",
    "ancient",
    "radiant",
    "brilliant",
    "shining",
    "dazzling",
    "glimmering",
    "glowing",
    "sparkling",
    "luminous",
    "bright",
    "beaming",
    "serene",
    "tranquil",
    "peaceful",
    "calm",
    "harmonious",
    "soothing",
    "gentle",
    "quiet",
    "still",
    "meditative",
    "adventure",
    "explore",
    "journey",
    "voyage",
    "expedition",
    "quest",
    "pioneer",
    "wanderer",
    "traveler",
    "nomad",
    "wisdom",
    "insight",
    "knowledge",
    "truth",
    "understanding",
    "clarity",
    "awareness",
    "intuition",
    "perception",
    "philosophy",
  ],

  landingPage: {
    title: "Effortless Text Behind Image Design With AI",
    subtitle:
      "Create stunning text behind image designs in seconds—free, unlimited, and hassle-free!",
    whyOurWebsite: {
      heading: `Why ${process.env.NEXT_PUBLIC_WEBSITE_NAME}?`,
      list: [
        {
          title: "AI Background Removal",
          desc: "Instantly erase backgrounds with precision.",
        },
        {
          title: "Custom Backgrounds",
          desc: "Choose from solid colors, gradients, and templates to match your style.",
        },
        {
          title: "Outline & Borders",
          desc: "Add creative glowing, colored, or gradient outlines to highlight your image.",
        },
        {
          title: "Rotate & Scale",
          desc: "Adjust your photo size and angle for the perfect fit.",
        },
        {
          title: "High-Quality Download",
          desc: "Get HD profile pictures for any platform.",
        },
      ],
    },
    howItWorks: {
      heading: `How it works`,
      list: [
        {
          title: "Upload Your Image",
          desc: "Drag and drop or select an image to start editing.",
        },
        {
          title: "Remove Background",
          desc: "Our AI automatically removes the background in seconds.",
        },
        {
          title: "Customize Your Profile Picture",
          desc: "Apply borders, outlines, colors, and backgrounds to match your aesthetic.",
        },
        {
          title: "Enhance & Adjust",
          desc: "Rotate, scale, and fine-tune your image for the perfect look.",
        },
        {
          title: "Download & Share",
          desc: "Save your new profile picture in high resolution and use it anywhere!",
        },
      ],
    },
    detailedList: [
      {
        title: "Simple to create and personalize",
        desc: `${process.env.NEXT_PUBLIC_WEBSITE_NAME} makes it easy for anyone to design a unique and professional logo, regardless of design experience.`,
      },
      {
        title: "Design a stunning logo in minutes",
        desc: " Our intuitive platform allows you to craft beautiful logos quickly, saving you time and effort.",
      },
      {
        title: `Effortless logo creation with ${process.env.NEXT_PUBLIC_WEBSITE_NAME}`,
        desc: "Choose from a wide selection of icons or upload your own, then customize with colors, gradients, and sizes.",
      },
      {
        title: "Obtain a high-quality logo for download",
        desc: "Export your logo in SVG or PNG formats, perfect for websites, social media, print, and branding.",
      },
      {
        title: "Perfect for all uses",
        desc: `Whether you need a logo for your business, personal project, or event, ${process.env.NEXT_PUBLIC_WEBSITE_NAME} provides the quality and flexibility you need.`,
      },
    ],
    faq: [
      {
        q: `Do I need any design experience to use ${process.env.NEXT_PUBLIC_WEBSITE_NAME}?`,
        a: `No, ${process.env.NEXT_PUBLIC_WEBSITE_NAME} is designed for users of all skill levels. Our intuitive interface and easy-to-use tools make it simple for anyone to create a professional logo.`,
      },

      {
        q: "Can I upload my own icons?",
        a: "Yes, you can upload your own icons and customize them using our platform.",
      },

      {
        q: "What formats are available for download?",
        a: "You can download your finished logo in SVG or PNG formats, ensuring high-quality results for any use.",
      },

      {
        q: "Is there a limit to the number of logos I can create?",
        a: `No, there are no limits on the number of logos you can create and download with ${process.env.NEXT_PUBLIC_WEBSITE_NAME}.`,
      },

      {
        q: "Can I use the logos I create for commercial purposes?",
        a: "Yes, once you download your logo, you have full rights to use it for any commercial or personal projects.",
      },
    ],
  },
};

export default textBehindImageConstants;
