const textBehindImageConstants = {
  randomWords: [
    "apple",
    "orange",
    "banana",
    "grape",
    "melon",
    "peach",
    "berry",
    "cherry",
    "lemon",
    "mango",
    "cloud",
    "storm",
    "rain",
    "thunder",
    "lightning",
    "wind",
    "breeze",
    "snow",
    "hail",
    "fog",
    "mountain",
    "valley",
    "hill",
    "river",
    "ocean",
    "lake",
    "forest",
    "jungle",
    "desert",
    "island",
    "sunrise",
    "sunset",
    "twilight",
    "moonlight",
    "starlight",
    "dawn",
    "dusk",
    "midnight",
    "noon",
    "evening",
    "shadow",
    "light",
    "dark",
    "glow",
    "spark",
    "flare",
    "flash",
    "shine",
    "beam",
    "luster",
    "dream",
    "vision",
    "fantasy",
    "wonder",
    "miracle",
    "mystery",
    "puzzle",
    "secret",
    "truth",
    "wisdom",
    "energy",
    "power",
    "strength",
    "force",
    "spirit",
    "soul",
    "mind",
    "thought",
    "idea",
    "inspiration",
    "fire",
    "water",
    "earth",
    "air",
    "metal",
    "wood",
    "stone",
    "crystal",
    "gold",
    "silver",
    "echo",
    "whisper",
    "voice",
    "song",
    "melody",
    "rhythm",
    "harmony",
    "tune",
    "symphony",
    "chorus",
    "peace",
    "love",
    "joy",
    "happiness",
    "hope",
    "faith",
    "kindness",
    "patience",
    "honor",
    "respect",
    "brave",
    "bold",
    "fearless",
    "strong",
    "gentle",
    "calm",
    "wild",
    "fierce",
    "silent",
    "loud",
    "cosmic",
    "galaxy",
    "universe",
    "star",
    "planet",
    "comet",
    "asteroid",
    "nebula",
    "orbit",
    "gravity",
    "time",
    "space",
    "infinity",
    "eternal",
    "limitless",
    "endless",
    "boundless",
    "timeless",
    "moment",
    "era",
    "zenith",
    "apex",
    "summit",
    "peak",
    "pinnacle",
    "height",
    "altitude",
    "horizon",
    "expanse",
    "beyond",
    "shadow",
    "phantom",
    "specter",
    "ghost",
    "spirit",
    "soul",
    "mystic",
    "oracle",
    "seer",
    "prophet",
    "flame",
    "ember",
    "blaze",
    "inferno",
    "firestorm",
    "pyro",
    "ignite",
    "burn",
    "scorch",
    "charcoal",
    "swift",
    "rapid",
    "fast",
    "quick",
    "lightning",
    "speed",
    "velocity",
    "momentum",
    "dash",
    "sprint",
    "deep",
    "vast",
    "profound",
    "boundless",
    "infinite",
    "expansive",
    "wide",
    "broad",
    "endless",
    "immeasurable",
    "frost",
    "ice",
    "glacier",
    "snowflake",
    "cold",
    "freeze",
    "chill",
    "crystal",
    "shiver",
    "icy",
    "arcane",
    "mystical",
    "enigmatic",
    "occult",
    "esoteric",
    "sacred",
    "hidden",
    "unknown",
    "forbidden",
    "ancient",
    "radiant",
    "brilliant",
    "shining",
    "dazzling",
    "glimmering",
    "glowing",
    "sparkling",
    "luminous",
    "bright",
    "beaming",
    "serene",
    "tranquil",
    "peaceful",
    "calm",
    "harmonious",
    "soothing",
    "gentle",
    "quiet",
    "still",
    "meditative",
    "adventure",
    "explore",
    "journey",
    "voyage",
    "expedition",
    "quest",
    "pioneer",
    "wanderer",
    "traveler",
    "nomad",
    "wisdom",
    "insight",
    "knowledge",
    "truth",
    "understanding",
    "clarity",
    "awareness",
    "intuition",
    "perception",
    "philosophy",
  ],

  landingPage: {
    title: "Effortless Text Behind Image Design With AI",
    subtitle:
      "Create stunning text behind image designs in seconds—free, unlimited, and hassle-free!",
    whyOurWebsite: {
      heading: `Why Text Behind Image?`,
      list: [
        {
          title: "Effortless Creativity",
          desc: "Easily place text behind objects in your image without complex editing tools.",
        },
        {
          title: "Full Customization",
          desc: "Adjust fonts, colors, sizes, and styles to match your vision.",
        },
        {
          title: "Smart Text Positioning",
          desc: "Seamlessly layer text within your photo with intuitive controls.",
        },
        {
          title: "High-Quality Results",
          desc: "Export professional-looking visuals in sharp, clear resolution.",
        },
        {
          title: "Fast & User-Friendly",
          desc: "Create stunning designs in minutes—no experience required.",
        },
      ],
    },
    faq: {
      heading: `Frequently Asked Questions`,
      list: [
        {
          q: "Do I need design experience to use this tool?",
          a: "Not at all! The tool is designed to be intuitive and beginner-friendly.",
        },
        {
          q: "Can I use any image format?",
          a: "Yes, popular formats like JPG, PNG, and WebP are supported.",
        },
        {
          q: "Can I edit the text after placing it behind the image?",
          a: "Yes, you can adjust or reposition the text anytime before downloading your design.",
        },
        {
          q: "Can I change font styles and colors?",
          a: "Definitely! You can choose from a variety of fonts, colors, and text styles to match your vision.",
        },
        {
          q: "What kind of images work best with this tool?",
          a: "Images with clear subjects and backgrounds give the best results when placing text behind objects.",
        },
      ],
    },
    detailedList: [
      {
        title: "Simple to create and personalize",
        desc: `${process.env.NEXT_PUBLIC_WEBSITE_NAME} makes it easy for anyone to design a unique and professional logo, regardless of design experience.`,
      },
      {
        title: "Design a stunning logo in minutes",
        desc: " Our intuitive platform allows you to craft beautiful logos quickly, saving you time and effort.",
      },
      {
        title: `Effortless logo creation with ${process.env.NEXT_PUBLIC_WEBSITE_NAME}`,
        desc: "Choose from a wide selection of icons or upload your own, then customize with colors, gradients, and sizes.",
      },
      {
        title: "Obtain a high-quality logo for download",
        desc: "Export your logo in SVG or PNG formats, perfect for websites, social media, print, and branding.",
      },
      {
        title: "Perfect for all uses",
        desc: `Whether you need a logo for your business, personal project, or event, ${process.env.NEXT_PUBLIC_WEBSITE_NAME} provides the quality and flexibility you need.`,
      },
    ],
  },
};

export default textBehindImageConstants;
